// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRChMELLAMjyXm_ZRwXTHvlYTt_pxOLrs',
    appId: '1:1052956156222:web:87fb58610bde1b21f38c6f',
    messagingSenderId: '1052956156222',
    projectId: 'budget-c0522',
    authDomain: 'budget-c0522.firebaseapp.com',
    storageBucket: 'budget-c0522.appspot.com',
    measurementId: 'G-4CPNXN6JVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8hbSL6K71DOkPJ72FMOWowk53Ld4ov8',
    appId: '1:1052956156222:android:8d66a43b64cbfea0f38c6f',
    messagingSenderId: '1052956156222',
    projectId: 'budget-c0522',
    storageBucket: 'budget-c0522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB4X1nArCyEu9OtpKk6SetFCtegJcVNXI',
    appId: '1:1052956156222:ios:a1bcf9b11154b72cf38c6f',
    messagingSenderId: '1052956156222',
    projectId: 'budget-c0522',
    storageBucket: 'budget-c0522.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB4X1nArCyEu9OtpKk6SetFCtegJcVNXI',
    appId: '1:1052956156222:ios:a1bcf9b11154b72cf38c6f',
    messagingSenderId: '1052956156222',
    projectId: 'budget-c0522',
    storageBucket: 'budget-c0522.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRChMELLAMjyXm_ZRwXTHvlYTt_pxOLrs',
    appId: '1:1052956156222:web:b547864898801f22f38c6f',
    messagingSenderId: '1052956156222',
    projectId: 'budget-c0522',
    authDomain: 'budget-c0522.firebaseapp.com',
    storageBucket: 'budget-c0522.appspot.com',
    measurementId: 'G-E4K9TGLQH5',
  );
}
